[package]
name = "cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
core = { path = "../core" }
checker = { path = "../checker" }
syntax = { path = "../syntax" }
wasm = { path = "../wasm" }
clap = { version = "4.4", features = ["derive"] }
schemars = "0.8"
serde_json = "1.0"
wat = "1.0"
wasmtime = "25.0"
